INSERT INTO LANGUAGES (ID, CODE) VALUES (1, 'ES');

insert into TEXTS (id, value, lang_id) values ('512', 'Alabama A & M University', '1');
insert into TEXTS (id, value, lang_id) values ('513', 'University of Alabama at Birmingham', '1');
insert into TEXTS (id, value, lang_id) values ('683', 'Amridge University', '1');
insert into TEXTS (id, value, lang_id) values ('688', 'University of Alabama in Huntsville', '1');
insert into TEXTS (id, value, lang_id) values ('699', 'Alabama State University', '1');
insert into TEXTS (id, value, lang_id) values ('702', 'The University of Alabama', '1');
insert into TEXTS (id, value, lang_id) values ('703', 'Central Alabama Community College', '1');
insert into TEXTS (id, value, lang_id) values ('760', 'Athens State University', '1');
insert into TEXTS (id, value, lang_id) values ('765', 'Auburn University at Montgomery', '1');
insert into TEXTS (id, value, lang_id) values ('768', 'Auburn University', '1');
insert into TEXTS (id, value, lang_id) values ('790', 'Birmingham Southern College', '1');
insert into TEXTS (id, value, lang_id) values ('791', 'Chattahoochee Valley Community College', '1');
insert into TEXTS (id, value, lang_id) values ('838', 'Concordia College Alabama', '1');
insert into TEXTS (id, value, lang_id) values ('839', 'South University-Montgomery', '1');
insert into TEXTS (id, value, lang_id) values ('844', 'Enterprise State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('849', 'James H Faulkner State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('888', 'Faulkner University', '1');
insert into TEXTS (id, value, lang_id) values ('893', 'Gadsden State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('966', 'New Beginning College of Cosmetology', '1');
insert into TEXTS (id, value, lang_id) values ('969', 'George C Wallace State Community College-Dothan', '1');
insert into TEXTS (id, value, lang_id) values ('982', 'George C Wallace State Community College-Hanceville', '1');
insert into TEXTS (id, value, lang_id) values ('983', 'George C Wallace State Community College-Selma', '1');
insert into TEXTS (id, value, lang_id) values ('986', 'Herzing University-Birmingham', '1');
insert into TEXTS (id, value, lang_id) values ('991', 'Huntingdon College', '1');
insert into TEXTS (id, value, lang_id) values ('992', 'Heritage Christian University', '1');
insert into TEXTS (id, value, lang_id) values ('1021', 'J F Drake State Community and Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('1022', 'Jacksonville State University', '1');
insert into TEXTS (id, value, lang_id) values ('1023', 'Jefferson Davis Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1024', 'Jefferson State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1025', 'John C Calhoun State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1026', 'Judson College', '1');
insert into TEXTS (id, value, lang_id) values ('1027', 'Lawson State Community College-Birmingham Campus', '1');
insert into TEXTS (id, value, lang_id) values ('1028', 'University of West Alabama', '1');
insert into TEXTS (id, value, lang_id) values ('1029', 'Lurleen B Wallace Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1030', 'Marion Military Institute', '1');
insert into TEXTS (id, value, lang_id) values ('1045', 'Miles College', '1');
insert into TEXTS (id, value, lang_id) values ('1048', 'University of Mobile', '1');
insert into TEXTS (id, value, lang_id) values ('1079', 'University of Montevallo', '1');
insert into TEXTS (id, value, lang_id) values ('1109', 'Northwest-Shoals Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1112', 'University of North Alabama', '1');
insert into TEXTS (id, value, lang_id) values ('1135', 'Northeast Alabama Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1138', 'Oakwood University', '1');
insert into TEXTS (id, value, lang_id) values ('1139', 'Alabama Southern Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1166', 'Prince Institute-Southeast', '1');
insert into TEXTS (id, value, lang_id) values ('1196', 'Reid State Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('1218', 'Bishop State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1219', 'Samford University', '1');
insert into TEXTS (id, value, lang_id) values ('1222', 'Selma University', '1');
insert into TEXTS (id, value, lang_id) values ('1223', 'Shelton State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1226', 'Snead State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1229', 'University of South Alabama', '1');
insert into TEXTS (id, value, lang_id) values ('1418', 'Spring Hill College', '1');
insert into TEXTS (id, value, lang_id) values ('1465', 'Southeastern Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('2497', 'Stillman College', '1');
insert into TEXTS (id, value, lang_id) values ('2498', 'Talladega College', '1');
insert into TEXTS (id, value, lang_id) values ('2513', 'H Councill Trenholm State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2514', 'Troy University', '1');
insert into TEXTS (id, value, lang_id) values ('2525', 'Tuskegee University', '1');
insert into TEXTS (id, value, lang_id) values ('2526', 'United States Sports Academy', '1');
insert into TEXTS (id, value, lang_id) values ('2527', 'Bevill State Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2530', 'University of Alaska Anchorage', '1');
insert into TEXTS (id, value, lang_id) values ('2588', 'Alaska Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('2593', 'University of Alaska Fairbanks', '1');
insert into TEXTS (id, value, lang_id) values ('2635', 'University of Alaska Southeast', '1');
insert into TEXTS (id, value, lang_id) values ('2642', 'Alaska Pacific University', '1');
insert into TEXTS (id, value, lang_id) values ('2678', 'AVTEC-Alaska's Institute of Technology', '1');
insert into TEXTS (id, value, lang_id) values ('2681', 'Charter College-Anchorage', '1');
insert into TEXTS (id, value, lang_id) values ('2741', 'Alaska Career College', '1');
insert into TEXTS (id, value, lang_id) values ('2829', 'Everest College-Phoenix', '1');
insert into TEXTS (id, value, lang_id) values ('2895', 'Collins College', '1');
insert into TEXTS (id, value, lang_id) values ('2912', 'Empire Beauty School-Paradise Valley', '1');
insert into TEXTS (id, value, lang_id) values ('1839', 'Empire Beauty School-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('1861', 'Thunderbird School of Global Management', '1');
insert into TEXTS (id, value, lang_id) values ('1928', 'American Indian College Inc', '1');
insert into TEXTS (id, value, lang_id) values ('1875', 'American Institute of Technology', '1');
insert into TEXTS (id, value, lang_id) values ('1899', 'Carrington College-Phoenix', '1');
insert into TEXTS (id, value, lang_id) values ('1933', 'Carrington College-Mesa', '1');
insert into TEXTS (id, value, lang_id) values ('1936', 'Carrington College-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('1939', 'CollegeAmerica-Flagstaff', '1');
insert into TEXTS (id, value, lang_id) values ('2010', 'Arizona Academy of Beauty-East', '1');
insert into TEXTS (id, value, lang_id) values ('2011', 'Arizona Automotive Institute', '1');
insert into TEXTS (id, value, lang_id) values ('2012', 'Brookline College-Phoenix', '1');
insert into TEXTS (id, value, lang_id) values ('2013', 'Arizona State University-Tempe', '1');
insert into TEXTS (id, value, lang_id) values ('2018', 'Arizona Western College', '1');
insert into TEXTS (id, value, lang_id) values ('2040', 'University of Arizona', '1');
insert into TEXTS (id, value, lang_id) values ('2043', 'Southwest University of Visual Arts-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('2044', 'Central Arizona College', '1');
insert into TEXTS (id, value, lang_id) values ('2045', 'Brown Mackie College-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('2046', 'Charles of Italy Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('2047', 'Cochise County Community College District', '1');
insert into TEXTS (id, value, lang_id) values ('2052', 'Empire Beauty School-Flagstaff', '1');
insert into TEXTS (id, value, lang_id) values ('2063', 'Empire Beauty School-Chandler', '1');
insert into TEXTS (id, value, lang_id) values ('2068', 'Cortiva Institute-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('2069', 'Avalon School of Cosmetology-Mesa', '1');
insert into TEXTS (id, value, lang_id) values ('2070', 'Eastern Arizona College', '1');
insert into TEXTS (id, value, lang_id) values ('2103', 'Embry-Riddle Aeronautical University-Prescott', '1');
insert into TEXTS (id, value, lang_id) values ('2104', 'Frank Lloyd Wright School of Architecture', '1');
insert into TEXTS (id, value, lang_id) values ('2111', 'Glendale Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2116', 'Grand Canyon University', '1');
insert into TEXTS (id, value, lang_id) values ('2145', 'International Academy of Hair Design', '1');
insert into TEXTS (id, value, lang_id) values ('2146', 'GateWay Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2147', 'Mesa Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2150', 'ITT Technical Institute-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('2159', 'ITT Technical Institute-Tempe', '1');
insert into TEXTS (id, value, lang_id) values ('2160', 'Mohave Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2161', 'Universal Technical Institute of Arizona Inc-Motorcycle Mechanics Institute Division', '1');
insert into TEXTS (id, value, lang_id) values ('2162', 'Dine College', '1');
insert into TEXTS (id, value, lang_id) values ('2165', 'Northern Arizona University', '1');
insert into TEXTS (id, value, lang_id) values ('2166', 'Northland Pioneer College', '1');
insert into TEXTS (id, value, lang_id) values ('2171', 'Ottawa University-Phoenix', '1');
insert into TEXTS (id, value, lang_id) values ('2192', 'Phoenix College', '1');
insert into TEXTS (id, value, lang_id) values ('2193', 'Cortiva Institute-Scottsdale', '1');
insert into TEXTS (id, value, lang_id) values ('2194', 'Pima Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2195', 'Pima Medical Institute-Tucson', '1');
insert into TEXTS (id, value, lang_id) values ('2196', 'Pima Medical Institute-Albuquerque', '1');
insert into TEXTS (id, value, lang_id) values ('2214', 'Prescott College', '1');
insert into TEXTS (id, value, lang_id) values ('2219', 'Refrigeration School Inc', '1');
insert into TEXTS (id, value, lang_id) values ('2220', 'Rio Salado College', '1');
insert into TEXTS (id, value, lang_id) values ('2221', 'Roberto-Venn School of Luthiery', '1');
insert into TEXTS (id, value, lang_id) values ('2241', 'Hair Academy of Safford', '1');
insert into TEXTS (id, value, lang_id) values ('2248', 'Scottsdale Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2249', 'South Mountain Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2252', 'Arizona Christian University', '1');
insert into TEXTS (id, value, lang_id) values ('2340', 'Tucson College', '1');
insert into TEXTS (id, value, lang_id) values ('2341', 'Universal Technical Institute of Arizona Inc', '1');
insert into TEXTS (id, value, lang_id) values ('2346', 'Western International University', '1');
insert into TEXTS (id, value, lang_id) values ('2349', 'Empire Beauty School-NW Phoenix', '1');
insert into TEXTS (id, value, lang_id) values ('2372', 'Yavapai College', '1');
insert into TEXTS (id, value, lang_id) values ('2373', 'University of Arkansas at Little Rock', '1');
insert into TEXTS (id, value, lang_id) values ('2382', 'University of Arkansas for Medical Sciences', '1');
insert into TEXTS (id, value, lang_id) values ('2403', 'ABC Beauty College Inc', '1');
insert into TEXTS (id, value, lang_id) values ('2425', 'Arkansas Baptist College', '1');
insert into TEXTS (id, value, lang_id) values ('242', 'Arkansas Beauty School-Little Rock', '1');
insert into TEXTS (id, value, lang_id) values ('245', 'Arkansas Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('246', 'Lyon College', '1');
insert into TEXTS (id, value, lang_id) values ('6', 'Arkansas College of Barbering and Hair Design', '1');
insert into TEXTS (id, value, lang_id) values ('7', 'Arthur's Beauty College Inc-Fort Smith', '1');
insert into TEXTS (id, value, lang_id) values ('14', 'University of Arkansas', '1');
insert into TEXTS (id, value, lang_id) values ('15', 'University of Arkansas at Pine Bluff', '1');
insert into TEXTS (id, value, lang_id) values ('18', 'Arkansas State University-Beebe', '1');
insert into TEXTS (id, value, lang_id) values ('19', 'Arkansas State University-Main Campus', '1');
insert into TEXTS (id, value, lang_id) values ('20', 'Arkansas Tech University', '1');
insert into TEXTS (id, value, lang_id) values ('25', 'University of Arkansas at Monticello', '1');
insert into TEXTS (id, value, lang_id) values ('26', 'Arthur's Beauty College Inc-Jacksonville', '1');
insert into TEXTS (id, value, lang_id) values ('27', 'Baptist Health College-Little Rock', '1');
insert into TEXTS (id, value, lang_id) values ('47', 'Black River Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('54', 'University of Central Arkansas', '1');
insert into TEXTS (id, value, lang_id) values ('55', 'Central Baptist College', '1');
insert into TEXTS (id, value, lang_id) values ('56', 'Cossatot Community College of the University of Arkansas', '1');
insert into TEXTS (id, value, lang_id) values ('121', 'Crowley's Ridge College', '1');
insert into TEXTS (id, value, lang_id) values ('2915', 'Crowley's Ridge Technical Institute', '1');
insert into TEXTS (id, value, lang_id) values ('2937', 'East Arkansas Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2959', 'Eastern College of Health Vocations-Little Rock', '1');
insert into TEXTS (id, value, lang_id) values ('2981', 'Imagine-Paul Mitchell Partner School', '1');
insert into TEXTS (id, value, lang_id) values ('2984', 'National Park Community College', '1');
insert into TEXTS (id, value, lang_id) values ('2985', 'University of Arkansas Community College-Batesville', '1');
insert into TEXTS (id, value, lang_id) values ('2986', 'Harding University', '1');
insert into TEXTS (id, value, lang_id) values ('2987', 'Henderson State University', '1');
insert into TEXTS (id, value, lang_id) values ('2988', 'Hendrix College', '1');
insert into TEXTS (id, value, lang_id) values ('2997', 'Hot Springs Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('2998', 'Jefferson Regional Medical Center School of Nursing', '1');
insert into TEXTS (id, value, lang_id) values ('2999', 'John Brown University', '1');
insert into TEXTS (id, value, lang_id) values ('3000', 'Lees School of Cosmetology', '1');
insert into TEXTS (id, value, lang_id) values ('3001', 'Career Academy of Hair Design', '1');
insert into TEXTS (id, value, lang_id) values ('3021', 'Academy of Salon and Spa', '1');
insert into TEXTS (id, value, lang_id) values ('3022', 'Arkansas State University Mid-South', '1');
insert into TEXTS (id, value, lang_id) values ('3023', 'Arkansas Northeastern College', '1');
insert into TEXTS (id, value, lang_id) values ('3024', 'Margaret's Hair Academy Inc', '1');
insert into TEXTS (id, value, lang_id) values ('3029', 'New Tyler Barber College Inc', '1');
insert into TEXTS (id, value, lang_id) values ('3220', 'North Arkansas College', '1');
insert into TEXTS (id, value, lang_id) values ('3031', 'Northwest Technical Institute', '1');
insert into TEXTS (id, value, lang_id) values ('3242', 'Ouachita Baptist University', '1');
insert into TEXTS (id, value, lang_id) values ('3243', 'College of the Ouachitas', '1');
insert into TEXTS (id, value, lang_id) values ('3040', 'Ozarka College', '1');
insert into TEXTS (id, value, lang_id) values ('3286', 'University of the Ozarks', '1');
insert into TEXTS (id, value, lang_id) values ('3042', 'University of Arkansas Community College-Morrilton', '1');
insert into TEXTS (id, value, lang_id) values ('3053', 'Philander Smith College', '1');
insert into TEXTS (id, value, lang_id) values ('3056', 'Phillips Community College of the University of Arkansas', '1');
insert into TEXTS (id, value, lang_id) values ('3057', 'Southeast Arkansas College', '1');
insert into TEXTS (id, value, lang_id) values ('3092', 'Professional Cosmetology Education Center', '1');
insert into TEXTS (id, value, lang_id) values ('3093', 'Pulaski Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('3098', 'University of Arkansas Community College-Hope', '1');
insert into TEXTS (id, value, lang_id) values ('3099', 'Rich Mountain Community College', '1');
insert into TEXTS (id, value, lang_id) values ('3100', 'Paul Mitchell the School-Arkansas', '1');
insert into TEXTS (id, value, lang_id) values ('3101', 'Searcy Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('3102', 'Shorter College', '1');
insert into TEXTS (id, value, lang_id) values ('3103', 'Williams Baptist College', '1');
insert into TEXTS (id, value, lang_id) values ('3104', 'South Arkansas Community College', '1');
insert into TEXTS (id, value, lang_id) values ('3122', 'Southern Arkansas University Main Campus', '1');
insert into TEXTS (id, value, lang_id) values ('3123', 'Southern Arkansas University Tech', '1');
insert into TEXTS (id, value, lang_id) values ('3124', 'Velvatex College of Beauty Culture', '1');
insert into TEXTS (id, value, lang_id) values ('3127', 'University of Arkansas-Fort Smith', '1');
insert into TEXTS (id, value, lang_id) values ('3157', 'Academy of Art University', '1');
insert into TEXTS (id, value, lang_id) values ('3287', 'ITT Technical Institute-Rancho Cordova', '1');
insert into TEXTS (id, value, lang_id) values ('3344', 'Academy of Chinese Culture and Health Sciences', '1');
insert into TEXTS (id, value, lang_id) values ('3361', 'The Academy of Radio and TV Broadcasting', '1');
insert into TEXTS (id, value, lang_id) values ('3368', 'Avalon School of Cosmetology-Alameda', '1');
insert into TEXTS (id, value, lang_id) values ('3430', 'College of Alameda', '1');
insert into TEXTS (id, value, lang_id) values ('3390', 'Allan Hancock College', '1');
insert into TEXTS (id, value, lang_id) values ('3391', 'American Academy of Dramatic Arts-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('3452', 'American Baptist Seminary of the West', '1');
insert into TEXTS (id, value, lang_id) values ('3478', 'American Film Institute Conservatory', '1');
insert into TEXTS (id, value, lang_id) values ('3522', 'American Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('3568', 'American Career College-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('3573', 'American Conservatory Theater', '1');
insert into TEXTS (id, value, lang_id) values ('3582', 'American River College', '1');
insert into TEXTS (id, value, lang_id) values ('3587', 'Antelope Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('3604', 'Art Center College of Design', '1');
insert into TEXTS (id, value, lang_id) values ('3609', 'Associated Technical College-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('3622', 'Associated Technical College-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('3674', 'Azusa Pacific University', '1');
insert into TEXTS (id, value, lang_id) values ('1266', 'Bakersfield College', '1');
insert into TEXTS (id, value, lang_id) values ('1269', 'Barstow Community College', '1');
insert into TEXTS (id, value, lang_id) values ('1270', 'Bellus Academy-National City', '1');
insert into TEXTS (id, value, lang_id) values ('1271', 'Bethesda University', '1');
insert into TEXTS (id, value, lang_id) values ('1272', 'Biola University', '1');
insert into TEXTS (id, value, lang_id) values ('1273', 'Brooks Institute', '1');
insert into TEXTS (id, value, lang_id) values ('1330', 'Brownson Technical School', '1');
insert into TEXTS (id, value, lang_id) values ('1335', 'Bryan University', '1');
insert into TEXTS (id, value, lang_id) values ('1700', 'Butte College', '1');
insert into TEXTS (id, value, lang_id) values ('1737', 'Phillips Graduate Institute', '1');
insert into TEXTS (id, value, lang_id) values ('1738', 'California Institute of Integral Studies', '1');
insert into TEXTS (id, value, lang_id) values ('85', 'Cabrillo College', '1');
insert into TEXTS (id, value, lang_id) values ('86', 'California Baptist University', '1');
insert into TEXTS (id, value, lang_id) values ('87', 'California College of the Arts', '1');
insert into TEXTS (id, value, lang_id) values ('88', 'University of California-Hastings College of Law', '1');
insert into TEXTS (id, value, lang_id) values ('89', 'California Institute of Technology', '1');
insert into TEXTS (id, value, lang_id) values ('90', 'California Lutheran University', '1');
insert into TEXTS (id, value, lang_id) values ('91', 'California Polytechnic State University-San Luis Obispo', '1');
insert into TEXTS (id, value, lang_id) values ('92', 'Alliant International University-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('93', 'California State University-Bakersfield', '1');
insert into TEXTS (id, value, lang_id) values ('94', 'California State University-Stanislaus', '1');
insert into TEXTS (id, value, lang_id) values ('95', 'California State University-San Bernardino', '1');
insert into TEXTS (id, value, lang_id) values ('96', 'California State Polytechnic University-Pomona', '1');
insert into TEXTS (id, value, lang_id) values ('97', 'California State University-Chico', '1');
insert into TEXTS (id, value, lang_id) values ('98', 'California State University-Dominguez Hills', '1');
insert into TEXTS (id, value, lang_id) values ('99', 'California State University-Fresno', '1');
insert into TEXTS (id, value, lang_id) values ('100', 'California State University-Fullerton', '1');
insert into TEXTS (id, value, lang_id) values ('101', 'California State University-East Bay', '1');
insert into TEXTS (id, value, lang_id) values ('102', 'California State University-Long Beach', '1');
insert into TEXTS (id, value, lang_id) values ('103', 'California State University-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('104', 'California State University-Northridge', '1');
insert into TEXTS (id, value, lang_id) values ('105', 'California State University-Sacramento', '1');
insert into TEXTS (id, value, lang_id) values ('106', 'University of California-Berkeley', '1');
insert into TEXTS (id, value, lang_id) values ('107', 'University of California-Davis', '1');
insert into TEXTS (id, value, lang_id) values ('108', 'University of California-Irvine', '1');
insert into TEXTS (id, value, lang_id) values ('125', 'University of California-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('126', 'University of California-Riverside', '1');
insert into TEXTS (id, value, lang_id) values ('127', 'University of California-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('128', 'University of California-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('129', 'University of California-Santa Barbara', '1');
insert into TEXTS (id, value, lang_id) values ('130', 'University of California-Santa Cruz', '1');
insert into TEXTS (id, value, lang_id) values ('131', 'Sofia University', '1');
insert into TEXTS (id, value, lang_id) values ('132', 'California Beauty School', '1');
insert into TEXTS (id, value, lang_id) values ('133', 'California Christian College', '1');
insert into TEXTS (id, value, lang_id) values ('134', 'Le Cordon Bleu College of Culinary Arts-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('135', 'California Hair Design Academy', '1');
insert into TEXTS (id, value, lang_id) values ('136', 'California Institute of the Arts', '1');
insert into TEXTS (id, value, lang_id) values ('137', 'The California Maritime Academy', '1');
insert into TEXTS (id, value, lang_id) values ('138', 'California Western School of Law', '1');
insert into TEXTS (id, value, lang_id) values ('139', 'Canada College', '1');
insert into TEXTS (id, value, lang_id) values ('83', 'College of the Canyons', '1');
insert into TEXTS (id, value, lang_id) values ('84', 'Career Academy of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('140', 'Casa Loma College-Van Nuys', '1');
insert into TEXTS (id, value, lang_id) values ('141', 'CET-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('142', 'CET-Sobrato', '1');
insert into TEXTS (id, value, lang_id) values ('143', 'CET-El Centro', '1');
insert into TEXTS (id, value, lang_id) values ('144', 'CET-San Bernardino', '1');
insert into TEXTS (id, value, lang_id) values ('145', 'CET-Watsonville', '1');
insert into TEXTS (id, value, lang_id) values ('146', 'CET-Salinas', '1');
insert into TEXTS (id, value, lang_id) values ('147', 'Cerritos College', '1');
insert into TEXTS (id, value, lang_id) values ('148', 'Cerro Coso Community College', '1');
insert into TEXTS (id, value, lang_id) values ('149', 'Chabot College', '1');
insert into TEXTS (id, value, lang_id) values ('150', 'Chaffey College', '1');
insert into TEXTS (id, value, lang_id) values ('151', 'Chapman University', '1');
insert into TEXTS (id, value, lang_id) values ('152', 'Charles R Drew University of Medicine and Science', '1');
insert into TEXTS (id, value, lang_id) values ('153', 'Concordia University-Irvine', '1');
insert into TEXTS (id, value, lang_id) values ('154', 'San Diego Christian College', '1');
insert into TEXTS (id, value, lang_id) values ('155', 'Church Divinity School of the Pacific', '1');
insert into TEXTS (id, value, lang_id) values ('156', 'Citrus College', '1');
insert into TEXTS (id, value, lang_id) values ('157', 'Citrus Heights Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('158', 'City College of San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('159', 'Claremont Graduate University', '1');
insert into TEXTS (id, value, lang_id) values ('162', 'Claremont McKenna College', '1');
insert into TEXTS (id, value, lang_id) values ('188', 'Milan Institute-Visalia', '1');
insert into TEXTS (id, value, lang_id) values ('193', 'Clovis Adult Education', '1');
insert into TEXTS (id, value, lang_id) values ('208', 'Coastline Community College', '1');
insert into TEXTS (id, value, lang_id) values ('209', 'Cogswell College', '1');
insert into TEXTS (id, value, lang_id) values ('267', 'Coleman University', '1');
insert into TEXTS (id, value, lang_id) values ('268', 'COBA Academy', '1');
insert into TEXTS (id, value, lang_id) values ('273', 'Western University of Health Sciences', '1');
insert into TEXTS (id, value, lang_id) values ('274', 'Columbia College', '1');
insert into TEXTS (id, value, lang_id) values ('275', 'Columbia College-Hollywood', '1');
insert into TEXTS (id, value, lang_id) values ('276', 'El Camino College-Compton Center', '1');
insert into TEXTS (id, value, lang_id) values ('277', 'Contra Costa College', '1');
insert into TEXTS (id, value, lang_id) values ('278', 'Cosumnes River College', '1');
insert into TEXTS (id, value, lang_id) values ('279', 'Crafton Hills College', '1');
insert into TEXTS (id, value, lang_id) values ('177', 'Cuesta College', '1');
insert into TEXTS (id, value, lang_id) values ('178', 'Cuyamaca College', '1');
insert into TEXTS (id, value, lang_id) values ('189', 'Cypress College', '1');
insert into TEXTS (id, value, lang_id) values ('194', 'De Anza College', '1');
insert into TEXTS (id, value, lang_id) values ('195', 'Marinello Schools of Beauty-Hemet', '1');
insert into TEXTS (id, value, lang_id) values ('251', 'International School of Beauty Inc', '1');
insert into TEXTS (id, value, lang_id) values ('252', 'Dell'Arte International School of Physical Theatre', '1');
insert into TEXTS (id, value, lang_id) values ('253', 'College of the Desert', '1');
insert into TEXTS (id, value, lang_id) values ('417', 'Design Institute of San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('418', 'Diablo Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('511', 'Dominican University of California', '1');
insert into TEXTS (id, value, lang_id) values ('122', 'Dominican School of Philosophy & Theology', '1');
insert into TEXTS (id, value, lang_id) values ('213', 'East Los Angeles College', '1');
insert into TEXTS (id, value, lang_id) values ('220', 'Marinello Schools of Beauty-Santa Clara', '1');
insert into TEXTS (id, value, lang_id) values ('227', 'El Camino Community College District', '1');
insert into TEXTS (id, value, lang_id) values ('266', 'Elegance International', '1');
insert into TEXTS (id, value, lang_id) values ('290', 'Marinello Schools of Beauty-Burbank', '1');
insert into TEXTS (id, value, lang_id) values ('295', 'Marinello Schools of Beauty-Moreno Valley', '1');
insert into TEXTS (id, value, lang_id) values ('296', 'Emperor's College of Traditional Oriental Medicine', '1');
insert into TEXTS (id, value, lang_id) values ('321', 'Empire College', '1');
insert into TEXTS (id, value, lang_id) values ('328', 'Evergreen Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('331', 'Fashion Institute of Design & Merchandising-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('332', 'Fashion Institute of Design & Merchandising-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('351', 'Fashion Institute of Design & Merchandising-Orange County', '1');
insert into TEXTS (id, value, lang_id) values ('352', 'Feather River Community College District', '1');
insert into TEXTS (id, value, lang_id) values ('353', 'Federico Beauty Institute', '1');
insert into TEXTS (id, value, lang_id) values ('356', 'Fielding Graduate University', '1');
insert into TEXTS (id, value, lang_id) values ('359', 'Five Branches University', '1');
insert into TEXTS (id, value, lang_id) values ('372', 'Redondo Beach Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('377', 'Foothill College', '1');
insert into TEXTS (id, value, lang_id) values ('378', 'Franciscan School of Theology', '1');
insert into TEXTS (id, value, lang_id) values ('379', 'Fredrick and Charles Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('380', 'Fresno City College', '1');
insert into TEXTS (id, value, lang_id) values ('389', 'Fresno Pacific University', '1');
insert into TEXTS (id, value, lang_id) values ('396', 'Fuller Theological Seminary in California', '1');
insert into TEXTS (id, value, lang_id) values ('399', 'Fullerton College', '1');
insert into TEXTS (id, value, lang_id) values ('404', 'Gavilan College', '1');
insert into TEXTS (id, value, lang_id) values ('465', 'Gemological Institute of America-Carlsbad', '1');
insert into TEXTS (id, value, lang_id) values ('487', 'Glendale Community College', '1');
insert into TEXTS (id, value, lang_id) values ('535', 'Glendale Career College', '1');
insert into TEXTS (id, value, lang_id) values ('540', 'Golden Gate University-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('543', 'Golden West College', '1');
insert into TEXTS (id, value, lang_id) values ('552', 'Graduate Theological Union', '1');
insert into TEXTS (id, value, lang_id) values ('553', 'Grossmont College', '1');
insert into TEXTS (id, value, lang_id) values ('554', 'Salon Success Academy-Riverside', '1');
insert into TEXTS (id, value, lang_id) values ('565', 'Hartnell College', '1');
insert into TEXTS (id, value, lang_id) values ('603', 'Harvey Mudd College', '1');
insert into TEXTS (id, value, lang_id) values ('604', 'Heald College-Rancho Cordova', '1');
insert into TEXTS (id, value, lang_id) values ('611', 'Heald College-Fresno', '1');
insert into TEXTS (id, value, lang_id) values ('612', 'Heald College-San Jose', '1');
insert into TEXTS (id, value, lang_id) values ('1412', 'Heald College-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('620', 'Heald College-Concord', '1');
insert into TEXTS (id, value, lang_id) values ('621', 'Hilltop Beauty School', '1');
insert into TEXTS (id, value, lang_id) values ('622', 'Holy Names University', '1');
insert into TEXTS (id, value, lang_id) values ('623', 'Pacifica Graduate Institute', '1');
insert into TEXTS (id, value, lang_id) values ('1439', 'Humboldt State University', '1');
insert into TEXTS (id, value, lang_id) values ('1440', 'Humphreys College-Stockton and Modesto Campuses', '1');
insert into TEXTS (id, value, lang_id) values ('1974', 'Imperial Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('1975', 'Institute for Business and Technology', '1');
insert into TEXTS (id, value, lang_id) values ('1976', 'Interior Designers Institute', '1');
insert into TEXTS (id, value, lang_id) values ('1977', 'Toni & Guy Hairdressing Academy-Santa Monica', '1');
insert into TEXTS (id, value, lang_id) values ('2096', 'Irvine Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('2430', 'ITT Technical Institute-National City', '1');
insert into TEXTS (id, value, lang_id) values ('2459', 'ITT Technical Institute-San Dimas', '1');
insert into TEXTS (id, value, lang_id) values ('2462', 'ITT Technical Institute-Orange', '1');
insert into TEXTS (id, value, lang_id) values ('2491', 'Bellus Academy-El Cajon', '1');
insert into TEXTS (id, value, lang_id) values ('2494', 'John F. Kennedy University', '1');
insert into TEXTS (id, value, lang_id) values ('4465', 'American Jewish University', '1');
insert into TEXTS (id, value, lang_id) values ('4492', 'Reedley College', '1');
insert into TEXTS (id, value, lang_id) values ('4554', 'Life Pacific College', '1');
insert into TEXTS (id, value, lang_id) values ('5091', 'Argosy University-The Art Institute of California-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('5094', 'University of La Verne', '1');
insert into TEXTS (id, value, lang_id) values ('5737', 'Laguna College of Art and Design', '1');
insert into TEXTS (id, value, lang_id) values ('5750', 'Lake Tahoe Community College', '1');
insert into TEXTS (id, value, lang_id) values ('7230', 'Lancaster Beauty School', '1');
insert into TEXTS (id, value, lang_id) values ('7260', 'Laney College', '1');
insert into TEXTS (id, value, lang_id) values ('7914', 'Lassen Community College', '1');
insert into TEXTS (id, value, lang_id) values ('7842', 'Life Chiropractic College West', '1');
insert into TEXTS (id, value, lang_id) values ('7843', 'Lincoln University', '1');
insert into TEXTS (id, value, lang_id) values ('8287', 'Southern California Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('9926', 'La Sierra University', '1');
insert into TEXTS (id, value, lang_id) values ('9984', 'Loma Linda University', '1');
insert into TEXTS (id, value, lang_id) values ('9966', 'Long Beach City College', '1');
insert into TEXTS (id, value, lang_id) values ('9987', 'Southern California University of Health Sciences', '1');
insert into TEXTS (id, value, lang_id) values ('10567', 'Los Angeles Harbor College', '1');
insert into TEXTS (id, value, lang_id) values ('8206', 'Los Angeles Pierce College', '1');
insert into TEXTS (id, value, lang_id) values ('8259', 'Los Angeles Southwest College', '1');
insert into TEXTS (id, value, lang_id) values ('8393', 'Los Angeles Trade Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('8396', 'Los Angeles Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('8453', 'The Master's College and Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('8454', 'Los Angeles City College', '1');
insert into TEXTS (id, value, lang_id) values ('8538', 'Los Angeles County College of Nursing and Allied Health', '1');
insert into TEXTS (id, value, lang_id) values ('8562', 'Los Angeles Mission College', '1');
insert into TEXTS (id, value, lang_id) values ('8586', 'Los Medanos College', '1');
insert into TEXTS (id, value, lang_id) values ('8614', 'Argosy University-The Art Institute of California-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('8677', 'Loyola Marymount University', '1');
insert into TEXTS (id, value, lang_id) values ('8658', 'Lu Ross Academy', '1');
insert into TEXTS (id, value, lang_id) values ('8678', 'Manchester Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('8705', 'Tulare Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('8708', 'Lyles Fresno College of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('8751', 'Lytles Redwood Empire Beauty College Inc', '1');
insert into TEXTS (id, value, lang_id) values ('8816', 'MTI Business College Inc', '1');
insert into TEXTS (id, value, lang_id) values ('8817', 'MTI College', '1');
insert into TEXTS (id, value, lang_id) values ('8818', 'Brightwood College-Sacramento', '1');
insert into TEXTS (id, value, lang_id) values ('8991', 'Brightwood College-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('9047', 'Brightwood College-Vista', '1');
insert into TEXTS (id, value, lang_id) values ('9161', 'College of Marin', '1');
insert into TEXTS (id, value, lang_id) values ('9162', 'Marinello Schools of Beauty-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('9354', 'Marymount California University', '1');
insert into TEXTS (id, value, lang_id) values ('9355', 'Mendocino College', '1');
insert into TEXTS (id, value, lang_id) values ('9425', 'Menlo College', '1');
insert into TEXTS (id, value, lang_id) values ('9448', 'Merced College', '1');
insert into TEXTS (id, value, lang_id) values ('9485', 'Merritt College', '1');
insert into TEXTS (id, value, lang_id) values ('3713', 'Mills College', '1');
insert into TEXTS (id, value, lang_id) values ('3716', 'MiraCosta College', '1');
insert into TEXTS (id, value, lang_id) values ('3717', 'Marinello Schools of Beauty-San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('3720', 'Mission College', '1');
insert into TEXTS (id, value, lang_id) values ('3742', 'Modern Beauty Academy', '1');
insert into TEXTS (id, value, lang_id) values ('3743', 'Brightwood College-North Hollywood', '1');
insert into TEXTS (id, value, lang_id) values ('3744', 'Modesto Junior College', '1');
insert into TEXTS (id, value, lang_id) values ('3766', 'Moler Barber College', '1');
insert into TEXTS (id, value, lang_id) values ('3945', 'Middlebury Institute of International Studies at Monterey', '1');
insert into TEXTS (id, value, lang_id) values ('3948', 'Monterey Peninsula College', '1');
insert into TEXTS (id, value, lang_id) values ('3973', 'Moorpark College', '1');
insert into TEXTS (id, value, lang_id) values ('3983', 'Mt San Antonio College', '1');
insert into TEXTS (id, value, lang_id) values ('3990', 'Mount Saint Mary's University', '1');
insert into TEXTS (id, value, lang_id) values ('3993', 'Mt San Jacinto Community College District', '1');
insert into TEXTS (id, value, lang_id) values ('4011', 'Mueller College', '1');
insert into TEXTS (id, value, lang_id) values ('4040', 'Musicians Institute', '1');
insert into TEXTS (id, value, lang_id) values ('4563', 'Napa Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('4569', 'Everest College-Reseda', '1');
insert into TEXTS (id, value, lang_id) values ('5029', 'Everest College-Gardena', '1');
insert into TEXTS (id, value, lang_id) values ('5344', 'Everest College-Alhambra', '1');
insert into TEXTS (id, value, lang_id) values ('5345', 'Everest College-San Bernardino', '1');
insert into TEXTS (id, value, lang_id) values ('5717', 'The National Hispanic University', '1');
insert into TEXTS (id, value, lang_id) values ('5756', 'National Holistic Institute', '1');
insert into TEXTS (id, value, lang_id) values ('5821', 'National University', '1');
insert into TEXTS (id, value, lang_id) values ('6396', 'Newschool of Architecture and Design', '1');
insert into TEXTS (id, value, lang_id) values ('6482', 'Newberry School of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('7776', 'North Adrian's College of Beauty Inc', '1');
insert into TEXTS (id, value, lang_id) values ('7777', 'North-West College-Pomona', '1');
insert into TEXTS (id, value, lang_id) values ('7778', 'North-West College-West Covina', '1');
insert into TEXTS (id, value, lang_id) values ('7938', 'North-West College-Pasadena', '1');
insert into TEXTS (id, value, lang_id) values ('8107', 'Notre Dame de Namur University', '1');
insert into TEXTS (id, value, lang_id) values ('8108', 'Occidental College', '1');
insert into TEXTS (id, value, lang_id) values ('8516', 'Oceanside College of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('8894', 'Ohlone College', '1');
insert into TEXTS (id, value, lang_id) values ('8895', 'Orange Coast College', '1');
insert into TEXTS (id, value, lang_id) values ('8896', 'Otis College of Art and Design', '1');
insert into TEXTS (id, value, lang_id) values ('8951', 'Oxnard College', '1');
insert into TEXTS (id, value, lang_id) values ('9230', 'Hope International University', '1');
insert into TEXTS (id, value, lang_id) values ('9231', 'Concorde Career College-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('9242', 'Palo Alto University', '1');
insert into TEXTS (id, value, lang_id) values ('9277', 'Pacific Lutheran Theological Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('9278', 'Pacific Oaks College', '1');
insert into TEXTS (id, value, lang_id) values ('9279', 'Pacific School of Religion', '1');
insert into TEXTS (id, value, lang_id) values ('9280', 'Pacific States University', '1');
insert into TEXTS (id, value, lang_id) values ('9301', 'Pacific Union College', '1');
insert into TEXTS (id, value, lang_id) values ('9302', 'University of the Pacific', '1');
insert into TEXTS (id, value, lang_id) values ('9303', 'Palo Verde College', '1');
insert into TEXTS (id, value, lang_id) values ('9304', 'Palomar College', '1');
insert into TEXTS (id, value, lang_id) values ('9305', 'Paris Beauty College', '1');
insert into TEXTS (id, value, lang_id) values ('9334', 'Pasadena City College', '1');
insert into TEXTS (id, value, lang_id) values ('9339', 'Pepperdine University', '1');
insert into TEXTS (id, value, lang_id) values ('9486', 'Pitzer College', '1');
insert into TEXTS (id, value, lang_id) values ('9489', 'Platt College-San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('9508', 'Point Loma Nazarene University', '1');
insert into TEXTS (id, value, lang_id) values ('9509', 'Pomona College', '1');
insert into TEXTS (id, value, lang_id) values ('9510', 'Porterville College', '1');
insert into TEXTS (id, value, lang_id) values ('9511', 'Westwood College-South Bay', '1');
insert into TEXTS (id, value, lang_id) values ('9512', 'Professional Institute of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('9519', 'Santa Ana College', '1');
insert into TEXTS (id, value, lang_id) values ('9542', 'Pardee RAND Graduate School', '1');
insert into TEXTS (id, value, lang_id) values ('9557', 'Shasta School of Cosmetology', '1');
insert into TEXTS (id, value, lang_id) values ('9560', 'University of Redlands', '1');
insert into TEXTS (id, value, lang_id) values ('9561', 'College of the Redwoods', '1');
insert into TEXTS (id, value, lang_id) values ('9599', 'Salon Success Academy-Upland', '1');
insert into TEXTS (id, value, lang_id) values ('9622', 'Salon Success Academy-Corona', '1');
insert into TEXTS (id, value, lang_id) values ('9637', 'Rio Hondo College', '1');
insert into TEXTS (id, value, lang_id) values ('9650', 'Riverside City College', '1');
insert into TEXTS (id, value, lang_id) values ('3700', 'Argosy University-San Francisco Bay Area', '1');
insert into TEXTS (id, value, lang_id) values ('3787', 'Rosemead Beauty School', '1');
insert into TEXTS (id, value, lang_id) values ('3788', 'Dongguk University-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('4127', 'Rudolf Steiner College', '1');
insert into TEXTS (id, value, lang_id) values ('4128', 'Sacramento City College', '1');
insert into TEXTS (id, value, lang_id) values ('4129', 'Saddleback College', '1');
insert into TEXTS (id, value, lang_id) values ('4130', 'Samuel Merritt University', '1');
insert into TEXTS (id, value, lang_id) values ('4131', 'San Diego City College', '1');
insert into TEXTS (id, value, lang_id) values ('4132', 'Golf Academy of America-Carlsbad', '1');
insert into TEXTS (id, value, lang_id) values ('4133', 'San Diego Mesa College', '1');
insert into TEXTS (id, value, lang_id) values ('4134', 'San Diego Miramar College', '1');
insert into TEXTS (id, value, lang_id) values ('4135', 'San Diego State University', '1');
insert into TEXTS (id, value, lang_id) values ('4136', 'University of San Diego', '1');
insert into TEXTS (id, value, lang_id) values ('4137', 'San Francisco Art Institute', '1');
insert into TEXTS (id, value, lang_id) values ('4138', 'San Francisco Conservatory of Music', '1');
insert into TEXTS (id, value, lang_id) values ('4139', 'San Francisco State University', '1');
insert into TEXTS (id, value, lang_id) values ('4140', 'San Francisco Theological Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('4141', 'University of San Francisco', '1');
insert into TEXTS (id, value, lang_id) values ('4142', 'San Joaquin College of Law', '1');
insert into TEXTS (id, value, lang_id) values ('4143', 'San Joaquin Delta College', '1');
insert into TEXTS (id, value, lang_id) values ('4146', 'San Joaquin Valley College-Visalia', '1');
insert into TEXTS (id, value, lang_id) values ('4147', 'William Jessup University', '1');
insert into TEXTS (id, value, lang_id) values ('4148', 'San Jose City College', '1');
insert into TEXTS (id, value, lang_id) values ('4149', 'San Jose State University', '1');
insert into TEXTS (id, value, lang_id) values ('4158', 'College of San Mateo', '1');
insert into TEXTS (id, value, lang_id) values ('4343', 'Santa Barbara Business College-Bakersfield', '1');
insert into TEXTS (id, value, lang_id) values ('4487', 'Westwood College-Los Angeles', '1');
insert into TEXTS (id, value, lang_id) values ('4562', 'Santa Barbara Business College-Santa Maria', '1');
insert into TEXTS (id, value, lang_id) values ('4566', 'Santa Barbara City College', '1');
insert into TEXTS (id, value, lang_id) values ('5738', 'Santa Clara University', '1');
insert into TEXTS (id, value, lang_id) values ('5615', 'Santa Monica College', '1');
insert into TEXTS (id, value, lang_id) values ('5753', 'Santa Rosa Junior College', '1');
insert into TEXTS (id, value, lang_id) values ('5745', 'Saybrook University', '1');
insert into TEXTS (id, value, lang_id) values ('5860', 'Scripps College', '1');
insert into TEXTS (id, value, lang_id) values ('5861', 'Wyotech-Fremont', '1');
insert into TEXTS (id, value, lang_id) values ('5938', 'College of the Sequoias', '1');
insert into TEXTS (id, value, lang_id) values ('6214', 'Shasta Bible College and Graduate School', '1');
insert into TEXTS (id, value, lang_id) values ('6385', 'Shasta College', '1');
insert into TEXTS (id, value, lang_id) values ('6388', 'Sierra College', '1');
insert into TEXTS (id, value, lang_id) values ('6389', 'Sierra College of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('7020', 'Sierra Valley College of Court Reporting', '1');
insert into TEXTS (id, value, lang_id) values ('7369', 'Trinity Law School', '1');
insert into TEXTS (id, value, lang_id) values ('8227', 'Simpson University', '1');
insert into TEXTS (id, value, lang_id) values ('8228', 'College of the Siskiyous', '1');
insert into TEXTS (id, value, lang_id) values ('8777', 'Charles A Jones Career and Education Center', '1');
insert into TEXTS (id, value, lang_id) values ('8310', 'Skyline College', '1');
insert into TEXTS (id, value, lang_id) values ('8333', 'San Bernardino Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('8334', 'Saint Mary's College of California', '1');
insert into TEXTS (id, value, lang_id) values ('8403', 'Solano Community College', '1');
insert into TEXTS (id, value, lang_id) values ('8495', 'Sonoma State University', '1');
insert into TEXTS (id, value, lang_id) values ('9183', 'Pinnacle College', '1');
insert into TEXTS (id, value, lang_id) values ('9184', 'South Baylo University', '1');
insert into TEXTS (id, value, lang_id) values ('9185', 'South Coast College', '1');
insert into TEXTS (id, value, lang_id) values ('9186', 'Vanguard University of Southern California', '1');
insert into TEXTS (id, value, lang_id) values ('9187', 'Concorde Career College-Garden Grove', '1');
insert into TEXTS (id, value, lang_id) values ('9188', 'Southwestern College', '1');
insert into TEXTS (id, value, lang_id) values ('9223', 'Starr King School for the Ministry', '1');
insert into TEXTS (id, value, lang_id) values ('9259', 'Marshall B Ketchum University', '1');
insert into TEXTS (id, value, lang_id) values ('9260', 'Southern California Institute of Architecture', '1');
insert into TEXTS (id, value, lang_id) values ('9261', 'University of Southern California', '1');
insert into TEXTS (id, value, lang_id) values ('9264', 'Southwestern Law School', '1');
insert into TEXTS (id, value, lang_id) values ('9669', 'Taft College', '1');
insert into TEXTS (id, value, lang_id) values ('9676', 'Claremont School of Theology', '1');
insert into TEXTS (id, value, lang_id) values ('9697', 'Thomas Aquinas College', '1');
insert into TEXTS (id, value, lang_id) values ('9726', 'Marinello Schools of Beauty-Lake Forest', '1');
insert into TEXTS (id, value, lang_id) values ('9731', 'Epic Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('9738', 'United Education Institute-Huntington Park Campus', '1');
insert into TEXTS (id, value, lang_id) values ('9905', 'Concorde Career College-San Bernardino', '1');
insert into TEXTS (id, value, lang_id) values ('9840', 'Universal College of Beauty Inc-Los Angeles 1', '1');
insert into TEXTS (id, value, lang_id) values ('9893', 'Concorde Career College-North Hollywood', '1');
insert into TEXTS (id, value, lang_id) values ('9896', 'Ventura College', '1');
insert into TEXTS (id, value, lang_id) values ('9912', 'Victor Valley Beauty College Inc', '1');
insert into TEXTS (id, value, lang_id) values ('9913', 'Victor Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('9914', 'Berkeley City College', '1');
insert into TEXTS (id, value, lang_id) values ('9915', 'Walden University', '1');
insert into TEXTS (id, value, lang_id) values ('9916', 'Waynes College of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('9917', 'West Hills College-Coalinga', '1');
insert into TEXTS (id, value, lang_id) values ('9920', 'West Los Angeles College', '1');
insert into TEXTS (id, value, lang_id) values ('9921', 'West Valley College', '1');
insert into TEXTS (id, value, lang_id) values ('10667', 'Carrington College-Sacramento', '1');
insert into TEXTS (id, value, lang_id) values ('10700', 'Westminster Theological Seminary in California', '1');
insert into TEXTS (id, value, lang_id) values ('10701', 'Westmont College', '1');
insert into TEXTS (id, value, lang_id) values ('10749', 'Whittier College', '1');
insert into TEXTS (id, value, lang_id) values ('10764', 'Woodbury University', '1');
insert into TEXTS (id, value, lang_id) values ('10769', 'The Wright Institute', '1');
insert into TEXTS (id, value, lang_id) values ('10944', 'Western State College of Law at Argosy University', '1');
insert into TEXTS (id, value, lang_id) values ('11059', 'Thomas Jefferson School of Law', '1');
insert into TEXTS (id, value, lang_id) values ('11062', 'Yeshiva Ohr Elchonon Chabad West Coast Talmudical Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('11084', 'Yuba College', '1');
insert into TEXTS (id, value, lang_id) values ('11085', 'The Salon Professional Academy-Grand Junction', '1');
insert into TEXTS (id, value, lang_id) values ('11086', 'Adams State University', '1');
insert into TEXTS (id, value, lang_id) values ('11087', 'Aims Community College', '1');
insert into TEXTS (id, value, lang_id) values ('11131', 'Arapahoe Community College', '1');
insert into TEXTS (id, value, lang_id) values ('11260', 'Bel-Rea Institute of Animal Technology', '1');
insert into TEXTS (id, value, lang_id) values ('11261', 'Everest College-Colorado Springs', '1');
insert into TEXTS (id, value, lang_id) values ('11262', 'University of Colorado Denver/Anschutz Medical Campus', '1');
insert into TEXTS (id, value, lang_id) values ('11315', 'University of Colorado Colorado Springs', '1');
insert into TEXTS (id, value, lang_id) values ('11546', 'Redstone College', '1');
insert into TEXTS (id, value, lang_id) values ('11559', 'University of Colorado Boulder', '1');
insert into TEXTS (id, value, lang_id) values ('11611', 'Colorado Christian University', '1');
insert into TEXTS (id, value, lang_id) values ('11612', 'Colorado College', '1');
insert into TEXTS (id, value, lang_id) values ('11643', 'Concorde Career College-Aurora', '1');
insert into TEXTS (id, value, lang_id) values ('11660', 'The Art Institute of Colorado', '1');
insert into TEXTS (id, value, lang_id) values ('11663', 'Colorado Mountain College', '1');
insert into TEXTS (id, value, lang_id) values ('11681', 'Colorado Northwestern Community College', '1');
insert into TEXTS (id, value, lang_id) values ('11684', 'Colorado School of Mines', '1');
insert into TEXTS (id, value, lang_id) values ('11721', 'Colorado School of Trades', '1');
insert into TEXTS (id, value, lang_id) values ('13291', 'Colorado State University-Fort Collins', '1');
insert into TEXTS (id, value, lang_id) values ('13351', 'Colorado Technical University-Colorado Springs', '1');
insert into TEXTS (id, value, lang_id) values ('13352', 'Empire Beauty School-Lakewood', '1');
insert into TEXTS (id, value, lang_id) values ('13353', 'Community College of Aurora', '1');
insert into TEXTS (id, value, lang_id) values ('13371', 'CollegeAmerica-Denver', '1');
insert into TEXTS (id, value, lang_id) values ('13372', 'Delta Montrose Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('13373', 'Prince Institute-Rocky Mountains', '1');
insert into TEXTS (id, value, lang_id) values ('13374', 'Community College of Denver', '1');
insert into TEXTS (id, value, lang_id) values ('13375', 'Lincoln College of Technology-Denver', '1');
insert into TEXTS (id, value, lang_id) values ('13376', 'Denver Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('13394', 'Westwood College-Denver North', '1');
insert into TEXTS (id, value, lang_id) values ('13395', 'University of Denver', '1');
insert into TEXTS (id, value, lang_id) values ('13400', 'Emily Griffith Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('13401', 'Fort Lewis College', '1');
insert into TEXTS (id, value, lang_id) values ('13402', 'Front Range Community College', '1');
insert into TEXTS (id, value, lang_id) values ('9997', 'Glenwood Beauty Academy', '1');
insert into TEXTS (id, value, lang_id) values ('9998', 'Hair Dynamics Education Center', '1');
insert into TEXTS (id, value, lang_id) values ('10071', 'Iliff School of Theology', '1');
insert into TEXTS (id, value, lang_id) values ('10090', 'International Salon and Spa Academy', '1');
insert into TEXTS (id, value, lang_id) values ('10125', 'Lamar Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10563', 'Colorado Mesa University', '1');
insert into TEXTS (id, value, lang_id) values ('10152', 'Metropolitan State University of Denver', '1');
insert into TEXTS (id, value, lang_id) values ('10163', 'Morgan Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10164', 'Naropa University', '1');
insert into TEXTS (id, value, lang_id) values ('10167', 'National American University-Colorado Springs', '1');
insert into TEXTS (id, value, lang_id) values ('10168', 'National American University-Denver', '1');
insert into TEXTS (id, value, lang_id) values ('10169', 'Nazarene Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('10170', 'Northeastern Junior College', '1');
insert into TEXTS (id, value, lang_id) values ('10187', 'University of Northern Colorado', '1');
insert into TEXTS (id, value, lang_id) values ('10564', 'Otero Junior College', '1');
insert into TEXTS (id, value, lang_id) values ('10195', 'Everest College-Thornton', '1');
insert into TEXTS (id, value, lang_id) values ('10196', 'Pikes Peak Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10197', 'IBMC College', '1');
insert into TEXTS (id, value, lang_id) values ('10204', 'Pueblo Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10207', 'Red Rocks Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10208', 'Regis University', '1');
insert into TEXTS (id, value, lang_id) values ('10568', 'Rocky Mountain College of Art and Design', '1');
insert into TEXTS (id, value, lang_id) values ('10242', 'Montessori Education Center of the Rockies', '1');
insert into TEXTS (id, value, lang_id) values ('10244', 'Colorado State University-Pueblo', '1');
insert into TEXTS (id, value, lang_id) values ('10247', 'Pickens Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10252', 'Intellitec College-Colorado Springs', '1');
insert into TEXTS (id, value, lang_id) values ('10255', 'Intellitec College-Grand Junction', '1');
insert into TEXTS (id, value, lang_id) values ('10261', 'Trinidad State Junior College', '1');
insert into TEXTS (id, value, lang_id) values ('10271', 'Empire Beauty School-Thornton', '1');
insert into TEXTS (id, value, lang_id) values ('10316', 'Western State Colorado University', '1');
insert into TEXTS (id, value, lang_id) values ('10328', 'Albertus Magnus College', '1');
insert into TEXTS (id, value, lang_id) values ('10352', 'Paul Mitchell the School-Danbury', '1');
insert into TEXTS (id, value, lang_id) values ('10353', 'Asnuntuck Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10354', 'Branford Hall Career Institute-Branford Campus', '1');
insert into TEXTS (id, value, lang_id) values ('10357', 'Lincoln College of New England-Southington', '1');
insert into TEXTS (id, value, lang_id) values ('10569', 'Bridgeport Hospital School of Nursing', '1');
insert into TEXTS (id, value, lang_id) values ('10574', 'University of Bridgeport', '1');
insert into TEXTS (id, value, lang_id) values ('10575', 'Central Connecticut State University', '1');
insert into TEXTS (id, value, lang_id) values ('10584', 'Charter Oak State College', '1');
insert into TEXTS (id, value, lang_id) values ('10585', 'Connecticut Center for Massage Therapy-Newington', '1');
insert into TEXTS (id, value, lang_id) values ('10586', 'Connecticut College', '1');
insert into TEXTS (id, value, lang_id) values ('10597', 'Marinello Schools of Beauty-East Hartford', '1');
insert into TEXTS (id, value, lang_id) values ('10598', 'Porter and Chester Institute of Branford', '1');
insert into TEXTS (id, value, lang_id) values ('10599', 'University of Connecticut', '1');
insert into TEXTS (id, value, lang_id) values ('10602', 'Goodwin College', '1');
insert into TEXTS (id, value, lang_id) values ('10605', 'Lincoln Technical Institute-East Windsor', '1');
insert into TEXTS (id, value, lang_id) values ('10606', 'Eastern Connecticut State University', '1');
insert into TEXTS (id, value, lang_id) values ('10607', 'Fairfield University', '1');
insert into TEXTS (id, value, lang_id) values ('3675', 'Paul Mitchell the School-North Haven', '1');
insert into TEXTS (id, value, lang_id) values ('3678', 'Capital Community College', '1');
insert into TEXTS (id, value, lang_id) values ('4000', 'Rensselaer Hartford Graduate Center Inc', '1');
insert into TEXTS (id, value, lang_id) values ('4703', 'American Institute-West Hartford', '1');
insert into TEXTS (id, value, lang_id) values ('4725', 'Hartford Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('4726', 'University of Hartford', '1');
insert into TEXTS (id, value, lang_id) values ('4780', 'Holy Apostles College and Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('4789', 'Housatonic Community College', '1');
insert into TEXTS (id, value, lang_id) values ('5126', 'Lyme Academy College of Fine Arts', '1');
insert into TEXTS (id, value, lang_id) values ('5127', 'Manchester Community College', '1');
insert into TEXTS (id, value, lang_id) values ('5351', 'Naugatuck Valley Community College', '1');
insert into TEXTS (id, value, lang_id) values ('5616', 'Middlesex Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6903', 'Mitchell College', '1');
insert into TEXTS (id, value, lang_id) values ('8841', 'Three Rivers Community College', '1');
insert into TEXTS (id, value, lang_id) values ('8840', 'Lincoln Technical Institute-New Britain', '1');
insert into TEXTS (id, value, lang_id) values ('8917', 'New England Tractor Trailer Training School of Connecticut', '1');
insert into TEXTS (id, value, lang_id) values ('9979', 'University of New Haven', '1');
insert into TEXTS (id, value, lang_id) values ('10358', 'Ridley-Lowell Business & Technical Institute-New London', '1');
insert into TEXTS (id, value, lang_id) values ('10468', 'Norwalk Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10525', 'Northwestern Connecticut Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10391', 'Paier College of Art Inc', '1');
insert into TEXTS (id, value, lang_id) values ('10392', 'Marinello Schools of Beauty-Meriden', '1');
insert into TEXTS (id, value, lang_id) values ('6222', 'Porter and Chester Institute of Stratford', '1');
insert into TEXTS (id, value, lang_id) values ('6223', 'Post University', '1');
insert into TEXTS (id, value, lang_id) values ('6224', 'Quinebaug Valley Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6225', 'Quinnipiac University', '1');
insert into TEXTS (id, value, lang_id) values ('6230', 'Sacred Heart University', '1');
insert into TEXTS (id, value, lang_id) values ('6231', 'University of Saint Joseph', '1');
insert into TEXTS (id, value, lang_id) values ('6232', 'Gateway Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6233', 'St Vincent's College', '1');
insert into TEXTS (id, value, lang_id) values ('6234', 'Southern Connecticut State University', '1');
insert into TEXTS (id, value, lang_id) values ('6235', 'Stone Academy-Hamden', '1');
insert into TEXTS (id, value, lang_id) values ('6236', 'Tri-State College of Acupuncture', '1');
insert into TEXTS (id, value, lang_id) values ('6237', 'Trinity College', '1');
insert into TEXTS (id, value, lang_id) values ('6238', 'Tunxis Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6239', 'Wesleyan University', '1');
insert into TEXTS (id, value, lang_id) values ('6240', 'Western Connecticut State University', '1');
insert into TEXTS (id, value, lang_id) values ('6271', 'Yale-New Haven Hospital Dietetic Internship', '1');
insert into TEXTS (id, value, lang_id) values ('6932', 'Yale University', '1');
insert into TEXTS (id, value, lang_id) values ('6959', 'Margaret H Rollins School of Nursing at Beebe Medical Center', '1');
insert into TEXTS (id, value, lang_id) values ('6979', 'Dawn Career Institute Inc', '1');
insert into TEXTS (id, value, lang_id) values ('7004', 'Delaware Technical Community College-Owens', '1');
insert into TEXTS (id, value, lang_id) values ('7005', 'Delaware Technical Community College-Terry', '1');
insert into TEXTS (id, value, lang_id) values ('7014', 'Delaware Technical Community College-Stanton/Wilmington', '1');
insert into TEXTS (id, value, lang_id) values ('7015', 'Delaware State University', '1');
insert into TEXTS (id, value, lang_id) values ('7031', 'University of Delaware', '1');
insert into TEXTS (id, value, lang_id) values ('7032', 'Goldey-Beacom College', '1');
insert into TEXTS (id, value, lang_id) values ('7055', 'Schilling-Douglas School of Hair Design LLC', '1');
insert into TEXTS (id, value, lang_id) values ('7056', 'Wesley College', '1');
insert into TEXTS (id, value, lang_id) values ('7059', 'Wilmington University', '1');
insert into TEXTS (id, value, lang_id) values ('7081', 'American University', '1');
insert into TEXTS (id, value, lang_id) values ('7082', 'Catholic University of America', '1');
insert into TEXTS (id, value, lang_id) values ('7085', 'University of the District of Columbia', '1');
insert into TEXTS (id, value, lang_id) values ('7116', 'Pontifical Faculty of the Immaculate Conception at the Dominican House of Studies', '1');
insert into TEXTS (id, value, lang_id) values ('7121', 'Gallaudet University', '1');
insert into TEXTS (id, value, lang_id) values ('7122', 'George Washington University', '1');
insert into TEXTS (id, value, lang_id) values ('7123', 'Georgetown University', '1');
insert into TEXTS (id, value, lang_id) values ('7144', 'Howard University', '1');
insert into TEXTS (id, value, lang_id) values ('7046', 'Medtech Institute', '1');
insert into TEXTS (id, value, lang_id) values ('7145', 'Strayer University-District of Columbia', '1');
insert into TEXTS (id, value, lang_id) values ('7156', 'National Conservatory of Dramatic Arts', '1');
insert into TEXTS (id, value, lang_id) values ('7157', 'Trinity Washington University', '1');
insert into TEXTS (id, value, lang_id) values ('7158', 'Wesley Theological Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('7161', 'Wyotech-Daytona', '1');
insert into TEXTS (id, value, lang_id) values ('7162', 'The Art Institute of Fort Lauderdale', '1');
insert into TEXTS (id, value, lang_id) values ('7165', 'Atlantic Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('7472', 'The Baptist College of Florida', '1');
insert into TEXTS (id, value, lang_id) values ('7185', 'Barry University', '1');
insert into TEXTS (id, value, lang_id) values ('7186', 'Gooding Institute of Nurse Anesthesia', '1');
insert into TEXTS (id, value, lang_id) values ('7206', 'Bethune-Cookman University', '1');
insert into TEXTS (id, value, lang_id) values ('7217', 'Lynn University', '1');
insert into TEXTS (id, value, lang_id) values ('7416', 'GUTI The Premier Beauty & Wellness Academy', '1');
insert into TEXTS (id, value, lang_id) values ('7423', 'Bradford-Union Technical Center', '1');
insert into TEXTS (id, value, lang_id) values ('7426', 'Eastern Florida State College', '1');
insert into TEXTS (id, value, lang_id) values ('7494', 'Broward College', '1');
insert into TEXTS (id, value, lang_id) values ('7495', 'Fortis College-Winter Park', '1');
insert into TEXTS (id, value, lang_id) values ('7516', 'Carlos Albizu University-Miami', '1');
insert into TEXTS (id, value, lang_id) values ('7597', 'College of Central Florida', '1');
insert into TEXTS (id, value, lang_id) values ('7870', 'Johnson University Florida', '1');
insert into TEXTS (id, value, lang_id) values ('7704', 'University of Central Florida', '1');
insert into TEXTS (id, value, lang_id) values ('7808', 'Charlotte Technical Center', '1');
insert into TEXTS (id, value, lang_id) values ('7894', 'Chipola College', '1');
insert into TEXTS (id, value, lang_id) values ('8143', 'Clearwater Christian College', '1');
insert into TEXTS (id, value, lang_id) values ('8144', 'Lorenzo Walker Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('8145', 'Daytona State College', '1');
insert into TEXTS (id, value, lang_id) values ('8148', 'South University-West Palm Beach', '1');
insert into TEXTS (id, value, lang_id) values ('8149', 'Eckerd College', '1');
insert into TEXTS (id, value, lang_id) values ('8150', 'Florida SouthWestern State College', '1');
insert into TEXTS (id, value, lang_id) values ('8170', 'Edward Waters College', '1');
insert into TEXTS (id, value, lang_id) values ('8171', 'Embry-Riddle Aeronautical University-Daytona Beach', '1');
insert into TEXTS (id, value, lang_id) values ('8172', 'Florida Agricultural and Mechanical University', '1');
insert into TEXTS (id, value, lang_id) values ('8173', 'Florida Atlantic University', '1');
insert into TEXTS (id, value, lang_id) values ('8174', 'Florida State College at Jacksonville', '1');
insert into TEXTS (id, value, lang_id) values ('8175', 'Flagler College-St Augustine', '1');
insert into TEXTS (id, value, lang_id) values ('8176', 'Florida College', '1');
insert into TEXTS (id, value, lang_id) values ('8177', 'Concorde Career Institute-Jacksonville', '1');
insert into TEXTS (id, value, lang_id) values ('8178', 'Concorde Career Institute-Miramar', '1');
insert into TEXTS (id, value, lang_id) values ('8203', 'Concorde Career Institute-Tampa', '1');
insert into TEXTS (id, value, lang_id) values ('8204', 'Adventist University of Health Sciences', '1');
insert into TEXTS (id, value, lang_id) values ('8205', 'Florida Institute of Technology', '1');
insert into TEXTS (id, value, lang_id) values ('10394', 'Florida Institute of Ultrasound Inc', '1');
insert into TEXTS (id, value, lang_id) values ('10395', 'Florida International University', '1');
insert into TEXTS (id, value, lang_id) values ('10398', 'Florida Keys Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10401', 'Florida Memorial University', '1');
insert into TEXTS (id, value, lang_id) values ('10406', 'Florida Career College-Miami', '1');
insert into TEXTS (id, value, lang_id) values ('10409', 'Florida School of Massage', '1');
insert into TEXTS (id, value, lang_id) values ('10410', 'Florida Southern College', '1');
insert into TEXTS (id, value, lang_id) values ('10411', 'Florida State University', '1');
insert into TEXTS (id, value, lang_id) values ('10412', 'Florida Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10413', 'University of Southernmost Florida', '1');
insert into TEXTS (id, value, lang_id) values ('10414', 'University of Florida', '1');
insert into TEXTS (id, value, lang_id) values ('10415', 'Everest University-Pompano Beach', '1');
insert into TEXTS (id, value, lang_id) values ('10416', 'Fort Pierce Beauty Academy', '1');
insert into TEXTS (id, value, lang_id) values ('10417', 'Full Sail University', '1');
insert into TEXTS (id, value, lang_id) values ('10418', 'George Stone Technical Center', '1');
insert into TEXTS (id, value, lang_id) values ('10419', 'George T Baker Aviation Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10420', 'Gulf Coast State College', '1');
insert into TEXTS (id, value, lang_id) values ('10421', 'Key College', '1');
insert into TEXTS (id, value, lang_id) values ('10422', 'Hillsborough Community College', '1');
insert into TEXTS (id, value, lang_id) values ('10423', 'Hobe Sound Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('10424', 'Hollywood Institute of Beauty Careers', '1');
insert into TEXTS (id, value, lang_id) values ('10425', 'Cortiva Institute-Florida', '1');
insert into TEXTS (id, value, lang_id) values ('10426', 'Indian River State College', '1');
insert into TEXTS (id, value, lang_id) values ('10427', 'Sanford-Brown College-Tampa', '1');
insert into TEXTS (id, value, lang_id) values ('10428', 'International Academy', '1');
insert into TEXTS (id, value, lang_id) values ('10429', 'AI Miami International University of Art and Design', '1');
insert into TEXTS (id, value, lang_id) values ('10446', 'ITT Technical Institute-Tampa', '1');
insert into TEXTS (id, value, lang_id) values ('10453', 'Jacksonville University', '1');
insert into TEXTS (id, value, lang_id) values ('10456', 'Jones College-Jacksonville', '1');
insert into TEXTS (id, value, lang_id) values ('10457', 'Keiser University-Ft Lauderdale', '1');
insert into TEXTS (id, value, lang_id) values ('10460', 'Heritage Institute-Ft Myers', '1');
insert into TEXTS (id, value, lang_id) values ('10463', 'La Belle Beauty School', '1');
insert into TEXTS (id, value, lang_id) values ('10469', 'Florida Gateway College', '1');
insert into TEXTS (id, value, lang_id) values ('10470', 'Lake Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10492', 'Lake-Sumter State College', '1');
insert into TEXTS (id, value, lang_id) values ('10497', 'Fort Myers Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10524', 'Lively Technical Center', '1');
insert into TEXTS (id, value, lang_id) values ('10526', 'Lindsey Hopkins Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10529', 'Loraines Academy & Spa', '1');
insert into TEXTS (id, value, lang_id) values ('10530', 'Luther Rice University & Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('10533', 'State College of Florida-Manatee-Sarasota', '1');
insert into TEXTS (id, value, lang_id) values ('10534', 'Manatee Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10545', 'Manhattan Hairstyling Academy', '1');
insert into TEXTS (id, value, lang_id) values ('10546', 'Traviss Career Center', '1');
insert into TEXTS (id, value, lang_id) values ('10547', 'Merryfield School of Pet Grooming', '1');
insert into TEXTS (id, value, lang_id) values ('10548', 'Trinity International University-Florida', '1');
insert into TEXTS (id, value, lang_id) values ('10553', 'Miami Lakes Educational Center and Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('10554', 'Miami Dade College', '1');
insert into TEXTS (id, value, lang_id) values ('10608', 'University of Miami', '1');
insert into TEXTS (id, value, lang_id) values ('10609', 'Orange Technical College-Mid Florida Campus', '1');
insert into TEXTS (id, value, lang_id) values ('10610', 'Beauty Schools of America-Miami', '1');
insert into TEXTS (id, value, lang_id) values ('10627', 'Remington College-Tampa Campus', '1');
insert into TEXTS (id, value, lang_id) values ('3820', 'Everest Institute-North Miami', '1');
insert into TEXTS (id, value, lang_id) values ('4950', 'Academy of Palm Beach', '1');
insert into TEXTS (id, value, lang_id) values ('5170', 'Lincoln College of Technology-West Palm Beach', '1');
insert into TEXTS (id, value, lang_id) values ('3829', 'Paul Mitchell the School-Jacksonville', '1');
insert into TEXTS (id, value, lang_id) values ('3836', 'North Florida Community College', '1');
insert into TEXTS (id, value, lang_id) values ('3841', 'University of North Florida', '1');
insert into TEXTS (id, value, lang_id) values ('3842', 'Northwood University-Florida', '1');
insert into TEXTS (id, value, lang_id) values ('3853', 'Nova Southeastern University', '1');
insert into TEXTS (id, value, lang_id) values ('3883', 'Northwest Florida State College', '1');
insert into TEXTS (id, value, lang_id) values ('3886', 'Everest University-North Orlando', '1');
insert into TEXTS (id, value, lang_id) values ('3887', 'Orange Technical College-Orlando Campus', '1');
insert into TEXTS (id, value, lang_id) values ('3892', 'Palm Beach Atlantic University', '1');
insert into TEXTS (id, value, lang_id) values ('3921', 'Palm Beach State College', '1');
insert into TEXTS (id, value, lang_id) values ('3978', 'Pasco-Hernando State College', '1');
insert into TEXTS (id, value, lang_id) values ('4035', 'Pensacola State College', '1');
insert into TEXTS (id, value, lang_id) values ('4062', 'Pinellas Technical College-Clearwater', '1');
insert into TEXTS (id, value, lang_id) values ('4069', 'Polk State College', '1');
insert into TEXTS (id, value, lang_id) values ('4091', 'Radford M Locklin Technical Center', '1');
insert into TEXTS (id, value, lang_id) values ('4096', 'Saint Vincent de Paul Regional Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('4184', 'Ridge Career Center', '1');
insert into TEXTS (id, value, lang_id) values ('4185', 'Ringling College of Art and Design', '1');
insert into TEXTS (id, value, lang_id) values ('4186', 'Robert Morgan Educational Center and Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4209', 'Rollins College', '1');
insert into TEXTS (id, value, lang_id) values ('4240', 'First Coast Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4243', 'Saint Leo University', '1');
insert into TEXTS (id, value, lang_id) values ('4244', 'St Petersburg College', '1');
insert into TEXTS (id, value, lang_id) values ('4255', 'Pinellas Technical College-St. Petersburg', '1');
insert into TEXTS (id, value, lang_id) values ('4304', 'Santa Fe College', '1');
insert into TEXTS (id, value, lang_id) values ('4346', 'Suncoast Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4347', 'Argosy University-Sarasota', '1');
insert into TEXTS (id, value, lang_id) values ('4364', 'Seminole State College of Florida', '1');
insert into TEXTS (id, value, lang_id) values ('4365', 'Sheridan Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4366', 'Saint John Vianney College Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('4367', 'Saint Johns River State College', '1');
insert into TEXTS (id, value, lang_id) values ('4368', 'South Florida State College', '1');
insert into TEXTS (id, value, lang_id) values ('4369', 'University of South Florida-Main Campus', '1');
insert into TEXTS (id, value, lang_id) values ('4370', 'St Thomas University', '1');
insert into TEXTS (id, value, lang_id) values ('4371', 'Stenotype Institute of Jacksonville Inc-Jacksonville', '1');
insert into TEXTS (id, value, lang_id) values ('4372', 'Stetson University', '1');
insert into TEXTS (id, value, lang_id) values ('4373', 'Southeastern University', '1');
insert into TEXTS (id, value, lang_id) values ('4374', 'Benes International School of Beauty', '1');
insert into TEXTS (id, value, lang_id) values ('4375', 'RIVEROAK Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4376', 'Tallahassee Community College', '1');
insert into TEXTS (id, value, lang_id) values ('4377', 'Talmudic College of Florida', '1');
insert into TEXTS (id, value, lang_id) values ('4384', 'Everest University-Tampa', '1');
insert into TEXTS (id, value, lang_id) values ('4385', 'Everest University-Largo', '1');
insert into TEXTS (id, value, lang_id) values ('4408', 'The University of Tampa', '1');
insert into TEXTS (id, value, lang_id) values ('4421', 'Taylor Technical Institute', '1');
insert into TEXTS (id, value, lang_id) values ('4422', 'Tom P Haney Technical Center', '1');
insert into TEXTS (id, value, lang_id) values ('4423', 'Trinity Baptist College', '1');
insert into TEXTS (id, value, lang_id) values ('4426', 'Trinity College of Florida', '1');
insert into TEXTS (id, value, lang_id) values ('4507', 'Fashion Focus Hair Academy', '1');
insert into TEXTS (id, value, lang_id) values ('4512', 'Valencia College', '1');
insert into TEXTS (id, value, lang_id) values ('4513', 'Warner University', '1');
insert into TEXTS (id, value, lang_id) values ('4680', 'Florida Panhandle Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4683', 'Webber International University', '1');
insert into TEXTS (id, value, lang_id) values ('4684', 'Rasmussen College-Florida', '1');
insert into TEXTS (id, value, lang_id) values ('4731', 'The University of West Florida', '1');
insert into TEXTS (id, value, lang_id) values ('4808', 'Orange Technical College-Westside Campus', '1');
insert into TEXTS (id, value, lang_id) values ('4907', 'William T McFatter Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('5171', 'Orange Technical College-Winter Park Campus', '1');
insert into TEXTS (id, value, lang_id) values ('5172', 'Withlacoochee Technical Institute', '1');
insert into TEXTS (id, value, lang_id) values ('5276', 'Abraham Baldwin Agricultural College', '1');
insert into TEXTS (id, value, lang_id) values ('5279', 'Agnes Scott College', '1');
insert into TEXTS (id, value, lang_id) values ('5366', 'Interactive College of Technology-Chamblee', '1');
insert into TEXTS (id, value, lang_id) values ('5373', 'Interactive College of Technology-Morrow', '1');
insert into TEXTS (id, value, lang_id) values ('5378', 'Albany Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('5483', 'Darton State College', '1');
insert into TEXTS (id, value, lang_id) values ('5486', 'Albany State University', '1');
insert into TEXTS (id, value, lang_id) values ('5229', 'Andrew College', '1');
insert into TEXTS (id, value, lang_id) values ('5298', 'Armstrong State University', '1');
insert into TEXTS (id, value, lang_id) values ('5299', 'The Art Institute of Atlanta', '1');
insert into TEXTS (id, value, lang_id) values ('5300', 'Georgia Career Institute', '1');
insert into TEXTS (id, value, lang_id) values ('5527', 'Atlanta Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('5530', 'Point University', '1');
insert into TEXTS (id, value, lang_id) values ('5531', 'Atlanta Metropolitan State College', '1');
insert into TEXTS (id, value, lang_id) values ('5536', 'Atlanta's John Marshall Law School', '1');
insert into TEXTS (id, value, lang_id) values ('5537', 'Atlanta School of Massage', '1');
insert into TEXTS (id, value, lang_id) values ('5570', 'Clark Atlanta University', '1');
insert into TEXTS (id, value, lang_id) values ('5571', 'Augusta Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('5572', 'Bainbridge State College', '1');
insert into TEXTS (id, value, lang_id) values ('5573', 'Bauder College', '1');
insert into TEXTS (id, value, lang_id) values ('5594', 'Beauty College of America', '1');
insert into TEXTS (id, value, lang_id) values ('5908', 'Berry College', '1');
insert into TEXTS (id, value, lang_id) values ('6290', 'Beulah Heights University', '1');
insert into TEXTS (id, value, lang_id) values ('5638', 'Brenau University', '1');
insert into TEXTS (id, value, lang_id) values ('5639', 'Brewton-Parker College', '1');
insert into TEXTS (id, value, lang_id) values ('5660', 'Brown College of Court Reporting', '1');
insert into TEXTS (id, value, lang_id) values ('5661', 'College of Coastal Georgia', '1');
insert into TEXTS (id, value, lang_id) values ('5662', 'West Georgia Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('5702', 'Carver Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('6326', 'Clayton  State University', '1');
insert into TEXTS (id, value, lang_id) values ('6327', 'Columbia Theological Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('6348', 'Columbus Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6349', 'Columbus State University', '1');
insert into TEXTS (id, value, lang_id) values ('6352', 'Georgia Northwestern Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6355', 'Covenant College', '1');
insert into TEXTS (id, value, lang_id) values ('6407', 'Dalton State College', '1');
insert into TEXTS (id, value, lang_id) values ('6410', 'Pro Way Hair School', '1');
insert into TEXTS (id, value, lang_id) values ('6411', 'South University-Savannah', '1');
insert into TEXTS (id, value, lang_id) values ('6461', 'East Georgia State College', '1');
insert into TEXTS (id, value, lang_id) values ('6462', 'Emmanuel College', '1');
insert into TEXTS (id, value, lang_id) values ('6463', 'Emory University', '1');
insert into TEXTS (id, value, lang_id) values ('6485', 'Georgia Highlands College', '1');
insert into TEXTS (id, value, lang_id) values ('6486', 'Fort Valley State University', '1');
insert into TEXTS (id, value, lang_id) values ('6507', 'Grady Health System Professional Schools', '1');
insert into TEXTS (id, value, lang_id) values ('6523', 'Georgia Institute of Technology-Main Campus', '1');
insert into TEXTS (id, value, lang_id) values ('6530', 'Georgia Southwestern State University', '1');
insert into TEXTS (id, value, lang_id) values ('6535', 'Georgia College and State University', '1');
insert into TEXTS (id, value, lang_id) values ('6536', 'Georgia Southern University', '1');
insert into TEXTS (id, value, lang_id) values ('6561', 'Georgia State University', '1');
insert into TEXTS (id, value, lang_id) values ('6653', 'University of Georgia', '1');
insert into TEXTS (id, value, lang_id) values ('6654', 'Gordon State College', '1');
insert into TEXTS (id, value, lang_id) values ('6655', 'Southern Crescent Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6656', 'Gupton Jones College of Funeral Service', '1');
insert into TEXTS (id, value, lang_id) values ('6657', 'Gwinnett College-Lilburn', '1');
insert into TEXTS (id, value, lang_id) values ('6658', 'Gwinnett Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6659', 'Interdenominational Theological Center', '1');
insert into TEXTS (id, value, lang_id) values ('6696', 'Kennesaw State University', '1');
insert into TEXTS (id, value, lang_id) values ('6699', 'LaGrange College', '1');
insert into TEXTS (id, value, lang_id) values ('6706', 'Lanier Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6717', 'Life University', '1');
insert into TEXTS (id, value, lang_id) values ('6767', 'Chattahoochee Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6768', 'Herzing University-Atlanta', '1');
insert into TEXTS (id, value, lang_id) values ('6769', 'Mercer University', '1');
insert into TEXTS (id, value, lang_id) values ('6770', 'Morehouse College', '1');
insert into TEXTS (id, value, lang_id) values ('6825', 'Morehouse School of Medicine', '1');
insert into TEXTS (id, value, lang_id) values ('6890', 'Moultrie Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6891', 'North Georgia Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('6892', 'Oglethorpe University', '1');
insert into TEXTS (id, value, lang_id) values ('3751', 'Paine College', '1');
insert into TEXTS (id, value, lang_id) values ('3758', 'Piedmont College', '1');
insert into TEXTS (id, value, lang_id) values ('3759', 'Portfolio Center', '1');
insert into TEXTS (id, value, lang_id) values ('3785', 'Reinhardt University', '1');
insert into TEXTS (id, value, lang_id) values ('3786', 'Savannah Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4117', 'Savannah College of Art and Design', '1');
insert into TEXTS (id, value, lang_id) values ('4118', 'Savannah State University', '1');
insert into TEXTS (id, value, lang_id) values ('4152', 'Shorter University', '1');
insert into TEXTS (id, value, lang_id) values ('4153', 'South Georgia Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4301', 'The Creative Circus', '1');
insert into TEXTS (id, value, lang_id) values ('4557', 'Spelman College', '1');
insert into TEXTS (id, value, lang_id) values ('4829', 'Southern Polytechnic State University', '1');
insert into TEXTS (id, value, lang_id) values ('4884', 'Southwest Georgia Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4937', 'Thomas University', '1');
insert into TEXTS (id, value, lang_id) values ('4938', 'Toccoa Falls College', '1');
insert into TEXTS (id, value, lang_id) values ('4943', 'Truett-McConnell College', '1');
insert into TEXTS (id, value, lang_id) values ('4944', 'Wiregrass Georgia Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('4945', 'Valdosta State University', '1');
insert into TEXTS (id, value, lang_id) values ('4946', 'Wesleyan College', '1');
insert into TEXTS (id, value, lang_id) values ('4947', 'University of West Georgia', '1');
insert into TEXTS (id, value, lang_id) values ('5795', 'Young Harris College', '1');
insert into TEXTS (id, value, lang_id) values ('5796', 'Heald College-Honolulu', '1');
insert into TEXTS (id, value, lang_id) values ('5817', 'Chaminade University of Honolulu', '1');
insert into TEXTS (id, value, lang_id) values ('5818', 'University of Hawaii at Hilo', '1');
insert into TEXTS (id, value, lang_id) values ('5941', 'University of Hawaii at Manoa', '1');
insert into TEXTS (id, value, lang_id) values ('5990', 'Hawaii Institute of Hair Design', '1');
insert into TEXTS (id, value, lang_id) values ('6001', 'Hawaii Pacific University', '1');
insert into TEXTS (id, value, lang_id) values ('6052', 'Honolulu Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6065', 'Kapiolani Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6066', 'Kauai Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6067', 'Leeward Community College', '1');
insert into TEXTS (id, value, lang_id) values ('6109', 'University of Hawaii Maui College', '1');
insert into TEXTS (id, value, lang_id) values ('6978', 'Med-Assist School of Hawaii Inc', '1');
insert into TEXTS (id, value, lang_id) values ('6179', 'World Medicine Institute', '1');
insert into TEXTS (id, value, lang_id) values ('6219', 'Travel Institute of the Pacific', '1');
insert into TEXTS (id, value, lang_id) values ('6220', 'University of Hawaii-West Oahu', '1');
insert into TEXTS (id, value, lang_id) values ('6221', 'Windward Community College', '1');
insert into TEXTS (id, value, lang_id) values ('14859', 'Carrington College-Boise', '1');
insert into TEXTS (id, value, lang_id) values ('14860', 'Boise Bible College', '1');
insert into TEXTS (id, value, lang_id) values ('14861', 'Boise State University', '1');
insert into TEXTS (id, value, lang_id) values ('14862', 'Eastern Idaho Technical College', '1');
insert into TEXTS (id, value, lang_id) values ('14863', 'Idaho State University', '1');
insert into TEXTS (id, value, lang_id) values ('14864', 'University of Idaho', '1');
insert into TEXTS (id, value, lang_id) values ('14865', 'The College of Idaho', '1');
insert into TEXTS (id, value, lang_id) values ('14866', 'Lewis-Clark State College', '1');
insert into TEXTS (id, value, lang_id) values ('14991', 'ITT Technical Institute-Boise', '1');
insert into TEXTS (id, value, lang_id) values ('14992', 'Aveda Institute-Twin Falls', '1');
insert into TEXTS (id, value, lang_id) values ('14993', 'Mr Leon's School of Hair Design-Moscow', '1');
insert into TEXTS (id, value, lang_id) values ('14994', 'North Idaho College', '1');
insert into TEXTS (id, value, lang_id) values ('15031', 'Northwest Nazarene University', '1');
insert into TEXTS (id, value, lang_id) values ('15032', 'The School of Hairstyling', '1');
insert into TEXTS (id, value, lang_id) values ('15033', 'Brigham Young University-Idaho', '1');
insert into TEXTS (id, value, lang_id) values ('15081', 'College of Southern Idaho', '1');
insert into TEXTS (id, value, lang_id) values ('15082', 'Adler University', '1');
insert into TEXTS (id, value, lang_id) values ('15083', 'Alvareitas College of Cosmetology-Edwardsville', '1');
insert into TEXTS (id, value, lang_id) values ('15084', 'Alvareitas College of Cosmetology-Godfrey', '1');
insert into TEXTS (id, value, lang_id) values ('15097', 'American Academy of Art', '1');
insert into TEXTS (id, value, lang_id) values ('15098', 'School of the Art Institute of Chicago', '1');
insert into TEXTS (id, value, lang_id) values ('15143', 'Augustana College', '1');
insert into TEXTS (id, value, lang_id) values ('15144', 'Aurora University', '1');
insert into TEXTS (id, value, lang_id) values ('15218', 'Tricoci University of Beauty Culture-Urbana', '1');
insert into TEXTS (id, value, lang_id) values ('15219', 'Southwestern Illinois College', '1');
insert into TEXTS (id, value, lang_id) values ('15249', 'Bethany Theological Seminary', '1');
insert into TEXTS (id, value, lang_id) values ('15250', 'Black Hawk College', '1');
insert into TEXTS (id, value, lang_id) values ('15251', 'Blackburn College', '1');
insert into TEXTS (id, value, lang_id) values ('15252', 'Blessing Rieman College of Nursing', '1');
insert into TEXTS (id, value, lang_id) values ('15253', 'Blessing Hospital School of Radiologic Technology', '1');
insert into TEXTS (id, value, lang_id) values ('15254', 'Bradley University', '1');
insert into TEXTS (id, value, lang_id) values ('15255', 'Paul Mitchell the School-Bradley', '1');
insert into TEXTS (id, value, lang_id) values ('15256', 'Cameo Beauty Academy', '1');